version: '3.8'

services:
  backend:
    build:
      context: ./todo_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://<your-rds-endpoint>:3306/todo_db
      SPRING_DATASOURCE_USERNAME: <aws-secrets-manager-username>
      SPRING_DATASOURCE_PASSWORD: <aws-secrets-manager-password>
    depends_on:
      - mysql

  frontend:
    build:
      context: ./todo_frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
      MYSQL_USER: <aws-secrets-manager-username>
      MYSQL_PASSWORD: <aws-secrets-manager-password>
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
